// cards-angular/src/app/pages/cards/cards.component.ts
import { Component } from '@angular/core';

import { CardsService } from '@core/services/cards.service';

@Component({
  selector: 'cards',
  templateUrl: './cards.component.html',
  styleUrls: ['./cards.component.scss']
})
export class CardsComponent {

  cards: Array<Array<string>> = [];

  path: string = '';
  back: string = '';
  show: boolean = false;

  constructor(
    public cardsService: CardsService
  ) {
    this.init();
  }

  init = async () => {
    const structure: any = await this.cardsService.getCardsConfig();
    
    this.path = '/assets/images/';
    this.back = structure.back + structure.format;

    structure.type.forEach((cardType: string) => {
      let type: Array<string> = [];
      structure.descriptor.forEach((desc: string) => {
        type.push(`${ cardType }-${ desc }${ structure.format }`);
      });
      this.cards.push(type);
    });
  };
  
  trackByType = (index: number, type: Array<string>): number => index;
  trackByCard = (index: number, card: string): string => card;

}


<div class="cards-wrapper">
  <div *ngFor="let type of cards; trackBy: trackByType" class="type-of-card">
    <ng-container *ngFor="let card of type; trackBy: trackByCard">
      <single-card [back]="back" [front]="card" [path]="path" [show]="show"></single-card>
    </ng-container>
  </div>
</div>

// cards-vue/src/views/Cards.vue

<template>
  <div class="card-wrapper">

    <div v-for="(type, index) in cards" :key="index">
      <span v-for="(card, cardIndex) in type" :key="cardIndex">
        <SingleCard
          v-bind:back="back"
          v-bind:front="card"
          v-bind:path="path"
          v-bind:show="false"></SingleCard>
      </span>
    </div>
  </div>
</template>

<script>
import CardsService from '../core/services/cards.service.js';
import SingleCard from '../components/SingleCard.vue';

export default {
  name: 'Cards',
  components: {
    SingleCard
  },
  data () {
    return {
      cards: [],
      path: '',
      back: ''
    }
  },
  async mounted () {
    const { cards, path, back } = await getConfig();
    console.log(cards);
    
    this.cards = cards;
    this.path = path;
    this.back = back;
  }
};

const getConfig = async () => {
  let cards = [];
  const structure = await CardsService.getCardsConfig();

  const path = '/assets/images/';
  const back = structure.back + structure.format;

  structure.type.forEach(cardType => {
    let type = [];
    structure.descriptor.forEach(desc => {
      type.push(`${ cardType }-${ desc }${ structure.format }`);
    });
    cards.push(type);
  });

  return { cards, path, back };
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.card-wrapper {
  padding: 1em;
  position: fixed;
  top: 3.5em;
  left: 0;
  width: 100vw;
  height: calc(100vh - 3em);
  overflow-y: auto;
  text-align: left;
}
</style>
