// cards-react/src/pages/cards/Cards.js

import './Cards.css';

import React, { useState, useEffect } from 'react';

import api from '../../core/services/api.js';

import SingleCard from '../../shared/single-card/SingleCard.js';

function Cards() {

  const [cards, setCards] = useState([]);
  const [path, setPath] = useState('');
  const [back, setBack] = useState('');

  const processCards = (structure) => {
    let cards = [];
  
    const path = '/assets/images/';
    const back = structure.back + structure.format;
  
    structure.type.forEach(cardType => {
      let type = [];
      structure.descriptor.forEach(desc => {
        type.push(`${ cardType }-${ desc }${ structure.format }`);
      });
      cards.push(type);
    });
  
    setPath(path);
    setBack(back);
    setCards(cards);
  };

  const initialize = () => {
    api.get('cards.json').then(response => {
      const structure = response.data;
      processCards(structure);
    }).catch(error => {
      console.log(error);
    });
  };

  useEffect(initialize, []);

  return (
    <div className="type-of-card">
      { cards.map((type, indexType) => (<div key={ `type-${ indexType }` }>
        { type.map((card, indexCard) =>
          <SingleCard key={ `card-${ indexCard }` } path={ path } front={ card } back={ back } show={ false }  />
        ) }
      </div>) ) }
    </div>
  );
}

export default Cards;

// cards-vue/src/views/Cards.vue

<template>
  <div class="card-wrapper">

    <div v-for="(type, index) in cards" :key="index">
      <span v-for="(card, cardIndex) in type" :key="cardIndex">
        <SingleCard
          v-bind:back="back"
          v-bind:front="card"
          v-bind:path="path"
          v-bind:show="false"></SingleCard>
      </span>
    </div>
  </div>
</template>

<script>
import CardsService from '../core/services/cards.service.js';
import SingleCard from '../components/SingleCard.vue';

export default {
  name: 'Cards',
  components: {
    SingleCard
  },
  data () {
    return {
      cards: [],
      path: '',
      back: ''
    }
  },
  async mounted () {
    const { cards, path, back } = await getConfig();
    console.log(cards);
    
    this.cards = cards;
    this.path = path;
    this.back = back;
  }
};

const getConfig = async () => {
  let cards = [];
  const structure = await CardsService.getCardsConfig();

  const path = '/assets/images/';
  const back = structure.back + structure.format;

  structure.type.forEach(cardType => {
    let type = [];
    structure.descriptor.forEach(desc => {
      type.push(`${ cardType }-${ desc }${ structure.format }`);
    });
    cards.push(type);
  });

  return { cards, path, back };
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.card-wrapper {
  padding: 1em;
  position: fixed;
  top: 3.5em;
  left: 0;
  width: 100vw;
  height: calc(100vh - 3em);
  overflow-y: auto;
  text-align: left;
}
</style>
