// cards-react/src/shared/single-card/SingleCard.js

import './SingleCard.css';

import React, { useState, useEffect } from 'react';

function SingleCard(props) {

  const [show, setShow] = useState(true);

  useEffect(() => {
    setShow(props.show);
  }, [props.show]);

  const getBack = () => props.path + props.back;
  const getFront = () => props.path + props.front;

  const cardClassNames = () => {
    let names = [ 'card' ];
    if (props?.disabled === true) {
      names.push('disabled');
    } else if (show === true) {
      names.push('show');
    }
    if (props.hasOwnProperty('addClass')) {
      names.push(props.addClass);
    }
    return names.join(' ');
  };

  const toggleShow = () => {
    if (props?.disabled === true) return;
    setShow(!show);
    if (show === false && props.hasOwnProperty('onVisibleClick')) {
      props.onVisibleClick();
    }
  };

  return (
    <div className={ cardClassNames() } onClick={ toggleShow }>
      <div className="content">
        <img src={ getFront() } className="front" alt="" />
        <img src={ getBack() } className="back" alt="" />
      </div>
    </div>
  );
}

export default SingleCard;

// cards-angular/src/app/features/single-card/single-card.component.ts
import { AfterViewInit, Component, Input } from '@angular/core';

@Component({
  selector: 'single-card',
  templateUrl: './single-card.component.html',
  styleUrls: ['./single-card.component.scss']
})
export class SingleCardComponent implements AfterViewInit {

  @Input() back: string = '';
  @Input() front: string = '';
  @Input() path: string = '';
  @Input() show: boolean = true;
  @Input() onVisibleClick: any;

  disabled: boolean = true;

  constructor() { }

  ngAfterViewInit() {
    setTimeout(this.checkDisabled, 100);
  }

  checkDisabled = () => {
    if (this.front !== this.back) {
      this.disabled = false;
    }
  };

  getBack = () => this.path + this.back;
  getFront = () => this.path + this.front;

  toggleShow = () => {
    if (this.disabled === true) return;
    this.show = !this.show;
    if (this.show === false) {
      this.handleOnVisibleClick();
    }
  };
  
  handleOnVisibleClick = () => {
    if (this.onVisibleClick !== undefined) {
      this.onVisibleClick();
    }
  };
}


<div class="card"
  [class.disabled]="disabled === true"
  [class.show]="disabled === false && show === true"
  (click)="disabled === false && toggleShow()">
  <div class="content">
    <img [src]="getFront()" class="front" />
    <img [src]="getBack()" class="back" />
  </div>
</div>
